name: PiggyCustomEnchants
main: PiggyCustomEnchants\Main
version: 1.1.3
api: [1.1.3, 2.0.0, 2.0.1, 3.0.0, 3.0.1, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5, 3.0.0-ALPHA6, 3.0.0-ALPHA7, 3.0.0-ALPHA8, 3.0.0-ALPHA9, 3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 3.0.0-ALPHA13, 3.0.0-ALPHA14, 3.0.0-ALPHA15]
load: POSTWORLD
author: DaPigGuy
translator: GamerSoiCon
permissions:
  piggycustomenchants:
    default: false
    description: "Sử dụng mọi thứ trong PiggyCustomEnchants"
    children:
      piggycustomenchants.command:
        default: op
        description: "Sử dụng tất cả lệnh trong PiggyCustomEnchants "
        children:
          piggycustomenchants.command.ce:
            default: op
            description: "Sử dụng /customenchant"
            children:
              piggycustomenchants.command.ce.about:
                default: true
                description: "Sử dụng /customenchant about"
              piggycustomenchants.command.ce.enchant:
                default: op
                description: "Sử dụng /customenchant enchant"
              piggycustomenchants.command.ce.help:
                default: true
                description: "Sử dụng /customenchant help"
              piggycustomenchants.command.ce.info:
                default: true
                description: "Sử dụng /customenchant info"
              piggycustomenchants.command.ce.list:
                default: true
                description: "Sử dụng /customenchant list"
      piggycustomenchants.overridecheck:
        default: false
        description: "Có thể dùng CustomEnchants Book lên Item và Enchant lên vật phẩm với bất cứ CE nào"
